name: Build

on: [push]

jobs:
  build:
    permissions:
      contents: write 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Build Windows exe
      if: startsWith(matrix.os, 'windows')
      env:
        UPX_PATH: C:\upx\upx.exe
      
      run: |
        # Install PyInstaller and upx
        pip install pyinstaller
        choco install upx
        
        # Build executable
        pyinstaller -n pvw_py --onefile --distpath . main.py

    - name: Install upx and shc for macOS
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install shc
        brew install upx

    - name: Install upx and shc for Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl shc

    - name: Build Linux and macOS exe
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
      env:
        UPX_PATH: /usr/local/bin/upx
      run: |
        # Install PyInstaller and upx
        pip3 install pyinstaller
        
        # Build executable
        pyinstaller --onefile main.py --distpath . -n pvw_py

    - name: Build Windows ps1 to exe
      if: startsWith(matrix.os, 'windows')
      shell: powershell
      run: |
        # install ps2exe
        Install-Module -Name ps2exe -Force
        import-module -Name ps2exe
        Invoke-PS2EXE -inputFile pvw.ps1 -outputFile pvw.exe

    - name: Build Linux/macOS sh to exe
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
      run: |      
        # Build executable
        shc -f pvw.sh -o pvw

    - name: Create archive for Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        # Install zip
        choco install zip
        # Create zip archive
        zip -r pvw.zip pvw_py.exe pvw.exe

    - name: Create archive for Linux and macOS
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
      run: |
        tar -czvf pvw.tar.gz pvw_py pvw

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: v0.0.1 # Replace with your program's version number
        allowUpdates: true
        commit: main
        body: |
          Release v0.0.1
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get os prefix
      id: get_os_prefix
      uses: actions/github-script@v6
      with:
        script: |
          var os = "${{ matrix.os }}".split('-')[0]
          if (os == "ubuntu") {
            os = "linux"
          }
          const suffix = "${{ matrix.os }}".startsWith("win") ? "zip" : "tar.gz"
          core.setOutput('os', os)
          core.setOutput('suffix', suffix)

    - name: Upload Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pvw.${{ steps.get_os_prefix.outputs.suffix }}
        asset_name: pvw_${{ steps.get_os_prefix.outputs.os }}_${{ matrix.arch }}.${{ steps.get_os_prefix.outputs.suffix }}
        asset_content_type: application/octet-stream
